#!/usr/bin/env node
/**
 * Generate images for all words using Pollinations.ai (free, no API key).
 * Usage: node scripts/generate-images.cjs [--dry-run] [--category animals] [--limit 10]
 * 
 * Reads: /tmp/habla_words_all.json (generated by parse_words.py)
 * Output: static/images/words/<filename>.webp
 */
const fs = require('fs');
const path = require('path');
const https = require('https');
const { execSync } = require('child_process');

// NOTE: generated images ship at full resolution. Run `make optimize-images`
// (`npm run optimize:images`) afterwards to resize/recompress them in place.

// ---- Config ----
const OUTPUT_DIR = path.join(__dirname, '..', 'static', 'images', 'words');
const WORDS_JSON = '/tmp/habla_words_all.json';
const RATE_LIMIT_MS = 1500; // Be nice to free API
const MAX_RETRIES = 3;
const IMG_SIZE = 512;

// ---- Parse args ----
const args = process.argv.slice(2);
const dryRun = args.includes('--dry-run');
const categoryFilter = args.find(a => a.startsWith('--category='))?.split('=')[1];
const limitArg = args.find(a => a.startsWith('--limit='));
const limit = limitArg ? parseInt(limitArg.split('=')[1]) : 0;
const resumeArg = args.find(a => a.startsWith('--resume='));
const resumeFrom = resumeArg ? resumeArg.split('=')[1] : null;

// ---- Load words from JSON ----
const words = JSON.parse(fs.readFileSync(WORDS_JSON, 'utf8'));

// ---- Prompt builder ----
// English prompts for better model comprehension, with Spanish word as subject
const PROMPT_TEMPLATES = {
  animals: (w) =>
    `A clear realistic photo of a ${w.word} (${w.definition}), on white background, well-lit, educational, no text`,
  food: (w) =>
    `A clear appetizing photo of ${w.word} (${w.definition}), on white background, food photography, no text`,
  'body-parts': (w) =>
    `A clear medical illustration of the ${w.word} on human body, clean style, white background, educational, no text`,
  clothing: (w) =>
    `A clear photo of a ${w.word} (${w.definition}), on white background, product photography, no text`,
  vehicles: (w) =>
    `A clear photo of a ${w.word} (${w.definition}), on white background, side view, no text`,
  tools: (w) =>
    `A clear photo of a ${w.word} (${w.definition}), on white background, studio shot, no text`,
  professions: (w) =>
    `A friendly cartoon illustration of a ${w.word} (${w.definition}), in uniform, white background, no text`,
  colors: (w) =>
    `A clean solid square of ${w.word} color, vibrant and saturated, minimalist, no text`,
  actions: (w) =>
    `A clear illustration of a person doing the action ${w.word} (${w.definition}), cartoon style, white background, no text`,
  places: (w) =>
    `A clear photo of a ${w.word} (${w.definition}), well-lit, clean composition, no text`,
  nature: (w) =>
    `A clear photo of ${w.word} (${w.definition}), on white background, nature photography, no text`,
  household: (w) =>
    `A clear photo of a ${w.word} (${w.definition}), on white background, product photography, no text`,
  emotions: (w) =>
    `A clear illustration of a face showing ${w.word} emotion (${w.definition}), cartoon style, white background, no text`,
  family: (w) =>
    `A friendly cartoon illustration of a ${w.word} (${w.definition}), white background, diverse, no text`,
  weather: (w) =>
    `A clear illustration of ${w.word} weather (${w.definition}), realistic, light background, no text`,
};

function buildPrompt(w) {
  const template = PROMPT_TEMPLATES[w.category] || PROMPT_TEMPLATES['nature'];
  return template(w);
}

// ---- Download image from Pollinations ----
function downloadImage(word, prompt, destPath) {
  return new Promise((resolve, reject) => {
    const encodedPrompt = encodeURIComponent(prompt);
    const url = `https://image.pollinations.ai/prompt/${encodedPrompt}?width=${IMG_SIZE}&height=${IMG_SIZE}&nologo=true`;
    
    const timeout = setTimeout(() => {
      reject(new Error('Download timeout (90s)'));
    }, 90000);
    
    const doDownload = (imageUrl) => {
      const protocol = imageUrl.startsWith('https') ? https : require('http');
      protocol.get(imageUrl, (res) => {
        if (res.statusCode === 301 || res.statusCode === 302) {
          doDownload(res.headers.location);
          return;
        }
        if (res.statusCode !== 200) {
          let body = '';
          res.on('data', c => body += c);
          res.on('end', () => { clearTimeout(timeout); reject(new Error(`HTTP ${res.statusCode}: ${body.substring(0, 200)}`)); });
          return;
        }
        const chunks = [];
        res.on('data', chunk => chunks.push(chunk));
        res.on('end', () => {
          clearTimeout(timeout);
          const buf = Buffer.concat(chunks);
          if (buf.length < 500) {
            reject(new Error(`Image too small (${buf.length}B)`));
            return;
          }
          // Detect format from magic bytes
          const isWebP = buf[0] === 0x52 && buf[1] === 0x49 && buf[2] === 0x46 && buf[3] === 0x46; // 'RIFF'
          const isJpeg = buf[0] === 0xFF && buf[1] === 0xD8; // JPEG SOI
          const isPng = buf[0] === 0x89 && buf[1] === 0x50; // PNG
          
          let savePath;
          if (isWebP) {
            savePath = destPath; // Already webp, save directly
          } else if (isJpeg) {
            savePath = destPath.replace('.webp', '_tmp.jpg');
          } else if (isPng) {
            savePath = destPath.replace('.webp', '_tmp.png');
          } else {
            savePath = destPath.replace('.webp', '_tmp.bin');
          }
          fs.writeFileSync(savePath, buf);
          resolve(savePath);
        });
      }).on('error', (e) => { clearTimeout(timeout); reject(e); });
    };
    doDownload(url);
  });
}

// Deterministic seed from word for reproducibility
function hashWord(word) {
  let hash = 0;
  for (let i = 0; i < word.length; i++) {
    const char = word.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash |= 0;
  }
  return Math.abs(hash) % 100000;
}

// ---- Convert to WebP ----
function convertToWebP(inputPath) {
  const webpPath = inputPath.replace(/\.[^.]+$/, '.webp');
  try {
    execSync(
      `python3 -c "from PIL import Image; img=Image.open('${inputPath}'); img=img.resize((512,512),Image.LANCZOS); img.save('${webpPath}','webp',quality=80)"`,
      { stdio: 'pipe' }
    );
    if (fs.existsSync(inputPath)) fs.unlinkSync(inputPath);
    return webpPath;
  } catch (e) {
    // If conversion fails, just rename
    if (fs.existsSync(inputPath) && !fs.existsSync(webpPath)) {
      fs.renameSync(inputPath, webpPath);
    }
    return webpPath;
  }
}

// ---- Main ----
async function main() {
  console.log('🎨 Habla Anomia — Image Generator (Pollinations.ai)');
  console.log(`   Words loaded: ${words.length}`);
  
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  
  // Filter
  let filtered = words;
  if (categoryFilter) {
    filtered = words.filter(w => w.category === categoryFilter);
    console.log(`   Category: "${categoryFilter}" → ${filtered.length} words`);
  }
  
  // Skip existing
  const existing = new Set(
    fs.readdirSync(OUTPUT_DIR).filter(f => f.endsWith('.webp')).map(f => f.replace('.webp', ''))
  );
  const toGenerate = filtered.filter(w => w.filename && !existing.has(w.filename));
  
  console.log(`   Existing: ${filtered.length - toGenerate.length}, To generate: ${toGenerate.length}`);
  
  if (dryRun) {
    console.log('\n📋 Dry run:');
    const sample = toGenerate.slice(0, limit || 10);
    for (const w of sample) {
      console.log(`\n  ${w.word} (${w.category}) → ${w.filename}.webp`);
      console.log(`  "${buildPrompt(w)}"`);
    }
    if (toGenerate.length > sample.length) {
      console.log(`\n  ... and ${toGenerate.length - sample.length} more`);
    }
    return;
  }
  
  let queue = toGenerate;
  if (limit > 0) queue = queue.slice(0, limit);
  if (resumeFrom) {
    const idx = queue.findIndex(w => w.word === resumeFrom || w.filename === resumeFrom);
    if (idx >= 0) { queue = queue.slice(idx); console.log(`   Resuming from "${resumeFrom}"`); }
  }
  
  console.log(`\n🚀 Generating ${queue.length} images...\n`);
  
  let success = 0, failed = 0, skipped = 0;
  
  for (let i = 0; i < queue.length; i++) {
    const w = queue[i];
    const destPath = path.join(OUTPUT_DIR, `${w.filename}.webp`);
    
    if (fs.existsSync(destPath)) { skipped++; continue; }
    
    const prompt = buildPrompt(w);
    console.log(`  [${i+1}/${queue.length}] ${w.word} (${w.category}) → ${w.filename}.webp`);
    
    let retries = 0, done = false;
    while (!done && retries < MAX_RETRIES) {
      try {
        const savedPath = await downloadImage(w.word, prompt, destPath);
        // Only convert if it's a non-webp temp file
        if (savedPath !== destPath) {
          convertToWebP(savedPath);
        }
        
        const stats = fs.statSync(destPath);
        if (stats.size < 500) throw new Error(`Too small (${stats.size}B)`);
        
        console.log(`     ✅ ${(stats.size / 1024).toFixed(1)}KB`);
        success++;
        done = true;
      } catch (e) {
        retries++;
        console.error(`     ❌ Attempt ${retries}: ${e.message}`);
        if (retries >= MAX_RETRIES) {
          console.error(`     💀 Failed: ${w.word}`);
          failed++;
          // Clean up any partial files
          try { fs.unlinkSync(destPath); } catch(e) {}
          try { fs.unlinkSync(destPath.replace('.webp', '_tmp.png')); } catch(e) {}
          done = true;
        } else {
          await new Promise(r => setTimeout(r, RATE_LIMIT_MS * retries));
        }
      }
    }
    
    if (i < queue.length - 1) {
      await new Promise(r => setTimeout(r, RATE_LIMIT_MS));
    }
  }
  
  const totalFiles = fs.readdirSync(OUTPUT_DIR).filter(f => f.endsWith('.webp')).length;
  console.log(`\n✨ Done! ✅ ${success} ❌ ${failed} ⏭️ ${skipped} | Total: ${totalFiles}`);
}

main().catch(e => { console.error('Fatal:', e); process.exit(1); });
